#Question 1
SELECT Name,registration_date 
	FROM user_info
WHERE operating_system='Android';

#Question 2
SELECT NAME, REGISTRATION_DATE 
	FROM USER_INFO
WHERE REGISTRATION_DATE >= '2023-07-14'
	ORDER BY REGISTRATION_DATE ASC;

#Question 3
SELECT R.NAME,M.NAME 
	FROM RESTAURANT_INFO R 
LEFT JOIN MENUITEMS M 
	ON R.RESTAURANT_ID=M.RESTAURANT_ID;

#Question 4
SELECT R.NAME, CONTACT_NUMBER, 
	COALESCE(M.NAME,'NO MENU ITEMS') MENU_ITEM_NAME, AVAILABILITY 
	FROM RESTAURANT_INFO R
LEFT OUTER JOIN MENUITEMS M
	ON R.RESTAURANT_ID = M.RESTAURANT_ID; 
    
#Question 5
SELECT NAME,COUNT(ORDER_ID) NUMBER_OF_ORDER 
	FROM USER_INFO A
INNER JOIN ORDERS B ON A.ID=B.USER_ID
	GROUP BY USER_ID
	ORDER BY NUMBER_OF_ORDER DESC;

#Question 6

SELECT R.NAME,AVG(PRICE) AVERAGE_PRICE 
	FROM MENUITEMS M 
INNER JOIN RESTAURANT_INFO R 
	ON M.RESTAURANT_ID=R.RESTAURANT_ID
GROUP BY R.RESTAURANT_ID
ORDER BY AVERAGE_PRICE ASC;

#Question 7
SELECT R.NAME,SUM(TOTAL_AMOUNT) TOTALS_SALES 
	FROM ORDERS O 
INNER JOIN RESTAURANT_INFO R 
	ON O.RESTAURANT_ID=R.RESTAURANT_ID
GROUP BY R.RESTAURANT_ID
ORDER BY R.NAME DESC LIMIT 1;

#Question 8
SELECT CITY_NAME,COUNT(ORDER_ID) ORDER_NUMBER 
	FROM ORDERS O 
LEFT JOIN
	(SELECT NAME,R.CITY_ID,C.CITY_NAME,RESTAURANT_ID FROM RESTAURANT_INFO R 
	LEFT JOIN CITY C
	ON R.CITY_ID = C.CITY_ID) M
    ON O.RESTAURANT_ID = M.RESTAURANT_ID
GROUP BY CITY_NAME ;

#Question 9
SELECT DISTINCT NAME 
	FROM RESTAURANT_INFO
WHERE RESTAURANT_ID IN
	(
    SELECT RESTAURANT_ID FROM MENUITEMS
    );
    
#Question 10
SELECT NAME, ORDER_NUMBER 
	FROM USER_INFO U
INNER JOIN 
    (SELECT USER_ID, COUNT(ORDER_ID) ORDER_NUMBER FROM ORDERS
		WHERE
		TOTAL_AMOUNT> (
			SELECT AVG(TOTAL_AMOUNT)
				FROM ORDERS)
            GROUP BY USER_ID 
         ) T
          ON U.ID=T.USER_ID;

#Question 11
SELECT NAME FROM USER_INFO
WHERE 
	SUBSTRING_INDEX(NAME, ' ', -1 ) LIKE 'S%'
    OR
    SUBSTRING_INDEX(NAME, ' ', -1 ) LIKE '%E';
    
#Question 12

SELECT R.NAME, TOTAL_AMOUNT 
	FROM RESTAURANT_INFO R
INNER JOIN
	(SELECT RESTAURANT_ID,COALESCE(SUM(TOTAL_AMOUNT),0 ) TOTAL_AMOUNT
		FROM ORDERS
	GROUP BY RESTAURANT_ID ) T
    ON R.RESTAURANT_ID=T.RESTAURANT_ID;

#Question 13
SELECT NAME, TOTAL_AMOUNT FROM PAYMENT_TYPE P
INNER JOIN 
(SELECT PAY_TYPE_ID, COUNT(PAY_TYPE_ID) TOTAL_AMOUNT
FROM PAYMENT_TRANSACTIONS
GROUP BY PAY_TYPE_ID) T
ON P.PAY_TYPE_ID=T.PAY_TYPE_ID;


 
